# Create custom.yml for changes

TBToken: 620818729:AAEKNhnctSqBYvxlUx_0KGfXe302bJ_A-UE
DBPath: db

TBM:
  Start: "_
  🤖 Приветствую!\n
  /search -> начать поиск собеседника.\n
  /next -> начать поиск нового собеседника (доступно только в беседе с случайным собеседником).\n
  /end -> закончить поиск или беседу.\n
  
  /help -> запросить помощь (по командам и функционалу).\n
  _"
