# Create custom.yml for changes

TBToken: 620818729:AAEKNhnctSqBYvxlUx_0KGfXe302bJ_A-UE
DataPath: data

TBMessages:
  Start: "_
  🤖 Приветствую!\n
  /search -> начать поиск собеседника.\n
  /end -> закончить поиск или беседу.\n
  
  /help -> запросить помощь (по командам и функционалу).\n
  _"

  SearchStarted: "Начинаю искать..."
  SearchAlreadyStarted: "Ты уже начал поиск."
  SearchStopped: "Поиск остановлен."

  RoomWelcome: "Добро пожаловать в #room #number{{.RoomNum}}"
  RoomNotInside: "Ты не в комнате. Чтобы найти собеседника, введи команду /search."

  MinorError: "Произошла какая-то ошибка... Извини. Я уже уведомил разработчиков."
